### ISSUE TITLE
Patch maker hang

### ISSUE THREAD

**Issue by markgibbons25** [jermdavis/PatchMaker#44]
It hanged after i clicked Browse.

Event viewer:
The program PatchMaker.App.exe version 1.5.1.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 82a8
 Start Time: 01d66ac4d1a45287
 Termination Time: 9
 Application Path: D:\sitecore\PatchMaker-v1.5.1\PatchMaker.App.exe
 Report Id: 80d3b6e6-7fbb-4a66-840a-e4eda2f9e0fd
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Cross-thread

Steps:
Extract prebuilt zip to D: drive
Open exe
Click browse
Hang

Environment:
Windows 10 2004

**Comment by jermdavis** [comment]
Can you confirm what you mean by "Click browse" there Mark? I'm thinking you mean clicking "File / Load Xml" from the menu bar after the app opens? But do correct me if you're referring to something else...

If so, does the "Open a file" dialog become visible at all before it hangs? Does the menu drop-down disappear? Or is it an instant hang that stops drawing the window as soon as you click?

I'm running the 2004 release of Windows on this laptop, and I've checked I can download and run the tool on this machine. That makes me suspect something about your local config is different to my machine...

A few things that spring to mind to check:
- Did you unblock the zip file before extracting the files?
- What version(s) of the .Net Framework do you have installed?
- Any network shares mapped that you don't currently have access to? (Network drives that require a VPN, but the VPN is down, for example?)
- Does Windows Explorer open OK, or do you see any hang/pauses when you open that up for the first time?
- Is your user a local admin on the machine?
- Any company-mandated security software running?

**Comment by jermdavis** [comment]
Closing due to lack of response.
