### ISSUE TITLE
cannot create a delete patch

### ISSUE THREAD

**Issue by AfshinZavvar** [jermdavis/PatchMaker#45]
can't create a delete patch
![image](https://user-images.githubusercontent.com/21095394/162374813-4f22bf97-0744-4cc5-97d1-388457266556.png)
![image](https://user-images.githubusercontent.com/21095394/162374942-005d1da6-c70f-4c54-a8d5-a7a639c96d21.png)

**Comment by jermdavis** [comment]
Thanks for raising the issue.

Can you give me some steps to reproduce the error please? The error message suggests the xPath to identify the specific config element isn't right, but it would be helpful to know exactly what you did to arrive at that error. Hopefully if I can reproduce the issue myself I can work out a fix for you.

**Comment by AfshinZavvar** [comment]
Not sure if I had to do anything manually.

1. Open the file
2. Search for "_content"
3. Select attribute and then select delete
4. Confirm
5. Generate patch

**Comment by jermdavis** [comment]
Ok - can verify the issue. At least part of it is that it's generating `/configuration[]/` in the xpath query - which is not valid. Manually tweaking that fixes the exception. But it still doesn't appear to generate the right result for the patch when that error doesn't occur.

Will investigate this further over the weeken, and see if I can work out how to fix it.

**Comment by jermdavis** [comment]
I think I've fixed the crash you were seeing, as with the latest release I can go through the steps you describe without an error.

Doing this, I note that the "preview what the patch will do" code doesn't generate the right results for this patch, however. I'm going to make that a separate issue, and look into that too. I suspect that's related to trying to apply a patch to source xml that was already a patch - so it may be a bit trickier to fix that. But I'll try...

Anyway, you can [grab v1.5.2 now](https://github.com/jermdavis/PatchMaker/releases/tag/v1.5.2) and see if that fixes the problem you saw before. Let me know if that version works for you, and this issue can be closed.

**Comment by AfshinZavvar** [comment]
Thank you very much for new release I can create patch now.
